### ISSUE TITLE
Problems loading the website

### ISSUE THREAD

**Issue by spidermike151** [stader-labs/hbarx-cli#2]
Hi so I have had my hbar staked through stader from the hashpack extension wallet using brave browser on a pc for about 3 months now and for i'd say almost a month now when I try to go to the stader hedera staking page it doesnt fully load and I have no way of acessing my staked coins, is stader still up and running? Did I get screwed out of my coins? or is there a simple fix, thanks to anyone with some insight because I'm read
<img width="960" alt="brave_mazCjJbKm6" src="https://user-images.githubusercontent.com/107374213/187054566-8b589129-e029-459c-8acc-c1d58bb0a5a2.png">
y to give up on this one.

**Comment by rahuljaguste** [comment]
Hey, @spidermike151 we are working towards fixing this issue. This happens for specific resolutions. A quick fix would be to use Ctrl and - on your keyboard which would zoom out the window and enable you to use the website.
Please reach out to our support team at https://t.me/StaderLabs_Hedera_Official if you are still unable to resolve the issue.
